import Head from 'next/head';
import { Poppins } from 'next/font/google';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Services from '@/components/Services';
import Value from '@/components/Value';
import Contact from '@/components/Contact';
import Gallery from '@/components/Gallery';
import Footer from '@/components/Footer';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Roofing Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${poppins.className}`}>
        <div className='app'>
          <div>
            <div className='white-gradient' />
            <Header />
            <Hero />
          </div>
          <Services />
          <Value />
          <Gallery />
          <Contact />
          <Footer />
        </div>
      </main>
    </>
  );
}
