import Head from 'next/head';
import { Poppins } from 'next/font/google';
import Header from '@/components/Header';
import Hero from '@/components/Hero';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Roofing Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${poppins.className}`}>
        <div className='app'>
          <Header />
          <Hero />
        </div>
      </main>
    </>
  );
}
